In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [29]:
# Scikit-learn imports
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score

In [30]:
# plotting
from matplotlib.colors import ListedColormap
def plot_decision_regions(X,y,classifier,test_idx=None,resolution=0.02):
    markers = ('o','s','^','v','<')
    colors = ('red','blue','lightgreen','gray','cyan')
    cmap = ListedColormap(colors[:len(np.unique(y))])

    x1_min, x1_max = X[:,0].min()-1, X[:,0].max()+1
    x2_min, x2_max = X[:,1].min()-1, X[:,1].max()+1

    xx1, xx2 = np.meshgrid(np.arange(x1_min,x1_max,resolution),
                           np.arange(x2_min,x2_max,resolution))
    
    lab = classifier.predict(np.array([xx1.ravel(),xx2.ravel()]).T)
    lab = lab.reshape(xx1.shape)
    plt.contourf(xx1,xx2,lab,alpha=0.3,cmap=cmap)
    plt.xlim(xx1.min(),xx1.max())
    plt.ylim(xx2.min(),xx2.max())

    for idx,cl in enumerate(np.unique(y)):
        plt.scatter(x=X[y==cl,0],
                    y=X[y==cl,1],
                    alpha=0.8, c=colors[idx],
                    marker=markers[idx],
                    label=f'Class {cl}',
                    edgecolor='black')
    # highlight test samples
    if test_idx:
        print(X.shape, test_idx)
        X_test, y_test = X[test_idx,:], y[test_idx]
        print(X_test.shape)
        plt.scatter(X_test[:,0],
                    X_test[:,1],
                    c='none',
                    edgecolor='black',
                    alpha=1.0,
                    linewidth=1,
                    marker='o',
                    s=100,
                    label='test set')

In [31]:
def load_iris_data():
    # load iris data from sklearn
    iris = datasets.load_iris()
    X = iris.data[:, [2, 3]]
    y = iris.target
    return X,y

def preprocess_data(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y,shuffle=True,)
    sc = StandardScaler()
    sc.fit(X_train)
    X_train_std = sc.transform(X_train)
    X_test_std = sc.transform(X_test)
    return X_train_std,X_test_std,y_train,y_test

In [32]:
from io import StringIO

In [33]:
csv_data = '''A,B,C,D
1,2,3,4
5,6,,8
10,11,12,'''

In [34]:
df=pd.read_csv(StringIO(csv_data))

In [35]:
df

    A   B     C    D
0   1   2   3.0  4.0
1   5   6   NaN  8.0
2  10  11  12.0  NaN

In [36]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [37]:
df.dropna(axis=1)

    A   B
0   1   2
1   5   6
2  10  11

In [38]:
df.dropna(how='all')

    A   B     C    D
0   1   2   3.0  4.0
1   5   6   NaN  8.0
2  10  11  12.0  NaN

In [39]:
from sklearn.impute import SimpleImputer

In [40]:
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(df.values)

In [41]:
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [42]:
df.fillna(df.mean())

    A   B     C    D
0   1   2   3.0  4.0
1   5   6   7.5  8.0
2  10  11  12.0  6.0

In [43]:
df

    A   B     C    D
0   1   2   3.0  4.0
1   5   6   NaN  8.0
2  10  11  12.0  NaN

In [44]:
df = pd.DataFrame([
    ['green','M',10.1,'class2'],
    ['red','L',13.5,'class1'],
    ['blue','XL',15.3,'class2']
    

])

In [46]:
df.columns=['color','size','price','classlabel']

In [47]:
df

   color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [48]:
size_mapping = {'XL':3, 'L':2, 'M':1}

In [49]:
df['size'] = df['size'].map(size_mapping)

In [50]:
df

   color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [52]:
class_mapping = {'class1':0, 'class2':1}
df['classlabel'] = df['classlabel'].map(class_mapping)

In [53]:
df

   color  size  price  classlabel
0  green     1   10.1           1
1    red     2   13.5           0
2   blue     3   15.3           1